Solving compilation issue on OS X 10.11.4
There was a missing include (err.h) for compiling ministat.c on OS X 10.11

ministat.c:483:3: warning: implicit declaration of function 'err' is invalid in C99 [-Wimplicit-function-declaration]
                err(1, "Cannot open %s", n);